
# NOTE - we do not create pods directly instead we create deployment or ReplicaSet

apiVersion: apps/v1
kind: deployment
metadata:
  name: sb-deployment
  labels:
    app: sb-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sb-app
  template:
    metadata:
      labels:
        app: sb-app
    spec:
      containers:
        - name: sb-container
          image: genieashwani/springboot-app:v1
          ports:
            - containerPort: 8080


